### PR TITLE
Show error when entering wrong credentials

### PR DESCRIPTION
**Pull request by NateshR**
Notifying user about invalid credentials when page doesn't load html content.

### CODE REVIEW

**Comment by AltNico** [comment]
Thank you very much, I also tried to solve this issue once but wasn't able to do so.
Your changes looks good, but you made some changes that are not needed. Also, you first commit is senseless.

Could you squash your commits and undo the changes to `config.xml` and `build.gradle`? If you have done this, I will merge this PR.

P.S.: This is how to do this on a commandline, I guess:
```
git reset --soft HEAD~2
git reset HEAD build.gradle src/main/res/values/config.xml
git commit -m "Show error when entering wrong credentials"
git push -f
```

**Comment by NateshR** [comment]
Its's done.

**Comment by AltNico** [comment]
Thank you, your changes looks good now.

Do you have tested your code? I tested it but it didn't work. `onPageFinished` only got called when the credentials were right. When they were wrong, `onPageFinished` didn't got called. Instead, `onReceivedHttpAuthRequest` got called in a loop, spamming the debug log.

If you tested it, can you give me your URL so that I can test it with wrong credentials. I don't want the  credentials, I just want to do this to test if it's a problem with your code or with my server.

**Comment by NateshR** [comment]
onPageFinished will be called all time even when the credentials are right or wrong. I am checking that if  credentials are right => page has some html => does have some height. I didn't test with any URL because I didn't found which accepts httpauth.

**Comment by AltNico** [comment]
Theoretical, you are right, but I guess `handler.proceed` calls `onReceivedHttpAuthRequest` and the page never finishs loading, so `onPageFinished` never gets called.

I temporarily added a `Log.d` call in `onPageFinished` when testing it but it never got called.

So thank you for your effort on this issue, but sadly it does not solve it.

**Comment by NateshR** [comment]
Let me try something else.

**Pull request closed without merging**
